(*
	NightScript Version 2 Reference Grammar
	This is the reference EBNF (Extended Backus-Naur Form) grammar for
	NightScript version 2. It is used as a reference for creating the
	hand-written recursive descent parser, rather than as an input for a parser
	generator. Because of this, the grammar may not be accurate.
*)

program = { stmt } END_OF_FILE ;
stmt    = "exit"
        | "call" LITERAL_STRING
        | "run" LITERAL_STRING
        | "sleep" expr [ "cs" | "ds" | "s" | "m" ]
        | "dialog" ( "show" | "hide" )
        | "name" [ LITERAL_STRING ]
        | "say" LITERAL_STRING
        | "player" ( "freeze" | "unfreeze" )
        | "quit" "title"
        | "pause"
        | "unpause"
        | "save"
        | "checkpoint"
        ;

expr = expr_or ;

(* Expression precedence levels from low to high: *)
expr_or         = expr_and { "or" expr_and } ;
expr_and        = expr_not { "and" expr_not } ;
expr_not        = "not" expr_not | expr_equality ;
expr_equality   = expr_comparison { ( "==" | "!=" ) expr_comparison } ;
expr_comparison = expr_sum { ( ">" | ">=" | "<" | "<=" ) expr_sum } ;
expr_sum        = expr_product { ( "+" | "-" ) expr_product } ;
expr_product    = expr_sign { "*" expr_sign } ;
expr_sign       = { "+" } ( "-" expr_sign | expr_primary ) ;
expr_primary    = "(" expr ")" | IDENTIFIER [ ":" IDENTIFIER ] | "false" | "true" | LITERAL_INT ;
